// Generated by delombok at Wed May 03 14:02:02 EDT 2023
/*
 * Table Wrapper API
 * Copyright (C) 2020  Spacious Team <spacious-team@ya.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.spacious_team.table_wrapper.api;

import static lombok.AccessLevel.PRIVATE;

public class OptionalTableColumn implements TableColumn {
    private final TableColumn column;
    private final AnyOfTableColumn anyOfTableColumn;

    public static OptionalTableColumn of(TableColumn column) {
        return new OptionalTableColumn(column, AnyOfTableColumn.of(column, TableColumn.NOCOLUMN));
    }

    @Override
    public int getColumnIndex(int firstColumnForSearch, ReportPageRow... headerRows) {
        try {
            return anyOfTableColumn.getColumnIndex(firstColumnForSearch, headerRows);
        } catch (Exception e) {
            throw new OptionalTableColumnNotFound(e);
        }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "OptionalTableColumn(column=" + this.column + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OptionalTableColumn)) return false;
        final OptionalTableColumn other = (OptionalTableColumn) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$column = this.column;
        final java.lang.Object other$column = other.column;
        if (this$column == null ? other$column != null : !this$column.equals(other$column)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OptionalTableColumn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $column = this.column;
        result = result * PRIME + ($column == null ? 43 : $column.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    private OptionalTableColumn(final TableColumn column, final AnyOfTableColumn anyOfTableColumn) {
        this.column = column;
        this.anyOfTableColumn = anyOfTableColumn;
    }
}
