// Generated by delombok at Sat Mar 25 11:54:07 EDT 2023
/*
 * Table Wrapper API
 * Copyright (C) 2020  Spacious Team <spacious-team@ya.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.spacious_team.table_wrapper.api;

public class RelativePositionTableColumn implements TableColumn {
    private final TableColumn column;
    private final int positionOffset;

    @Override
    public int getColumnIndex(int firstColumnForSearch, ReportPageRow... headerRows) {
        return column.getColumnIndex(firstColumnForSearch, headerRows) + positionOffset;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RelativePositionTableColumn(column=" + this.column + ", positionOffset=" + this.positionOffset + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RelativePositionTableColumn)) return false;
        final RelativePositionTableColumn other = (RelativePositionTableColumn) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.positionOffset != other.positionOffset) return false;
        final java.lang.Object this$column = this.column;
        final java.lang.Object other$column = other.column;
        if (this$column == null ? other$column != null : !this$column.equals(other$column)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RelativePositionTableColumn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.positionOffset;
        final java.lang.Object $column = this.column;
        result = result * PRIME + ($column == null ? 43 : $column.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    private RelativePositionTableColumn(final TableColumn column, final int positionOffset) {
        this.column = column;
        this.positionOffset = positionOffset;
    }

    @java.lang.SuppressWarnings("all")
    public static RelativePositionTableColumn of(final TableColumn column, final int positionOffset) {
        return new RelativePositionTableColumn(column, positionOffset);
    }
}
